name: 'Test github action'
on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: nightly
    steps:
      - uses: actions/checkout@v3
      - name: Compile and build github action
        run: |
          npm ci
          npm run all
      - name: Generate Wolfia github action and upload app
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          wolfia-api-key-id: ${{ vars.WOLFIA_API_KEY_ID }}
          wolfia-api-key-secret: ${{ secrets.WOLFIA_API_KEY_SECRET }}
          track-id: ${{ vars.TRACK_ID }}
          app-path: data/hacker.apk
